### ISSUE TITLE
There is an exception during Invite players phase

### ISSUE THREAD

**Issue by Darker** [Darker/auto-client#2]
Exception in thread "Thread-16" java.lang.ArrayIndexOutOfBoundsException: -1
	at cz.autoclient.autoclick.Rect.groupOverlapingRects(Rect.java:143)
	at cz.autoclient.autoclick.Rect.groupOverlapingRects(Rect.java:159)
	at cz.autoclient.autoclick.comvis.ScreenWatcher.bestMatches(ScreenWatcher.java:202)
	at cz.autoclient.autoclick.comvis.ScreenWatcher.findByAvgColor_isolated_matches(ScreenWatcher.java:198)
	at cz.autoclient.Automat.invite_lobby(Automat.java:697)
	at cz.autoclient.Automat.handleMatch(Automat.java:224)
	at cz.autoclient.Automat.run(Automat.java:65)

**Comment by Darker** [comment]
Fixed.
